services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
  data_collection:
    build: ./data-collection
    command: npm run populate
    depends_on:
      db:
        condition: service_healthy
  flask:
    build: ./frontend
    ports:
      - 5001:5001
  api:
    build: ./api
    ports:
    - 3000:3000
    depends_on:
      db:
        condition: service_healthy

volumes:
  db: